import { Country } from './country';

export const COUNTRIES: Country[] = [
    { id: 1,
    name: 'Argentina',
    capital: 'Buenos Aires',
    population: 43431886,
    continent: 'America',
    currency: 'Argentinean peso' },
    { id: 2,
    name: 'United Kingdom',
    capital: 'London',
    population: 59667840,
    continent: 'Europe',
    currency: 'British Pound' },
    { id: 3,
    name: 'Belgium',
    capital: 'Brussels',
    population: 10419050,
    continent: 'Europe',
    currency: 'Euro' },
    { id: 4,
    name: 'Cambodia',
    capital: 'Phnom Penh',
    population: 14071010,
    continent: 'Asia',
    currency: 'Cambodian Riel' },
    { id: 5,
    name: 'Romania',
    capital: 'Bucharest',
    population: 21711470,
    continent: 'Europe',
    currency: 'Romanian leu' },
    { id: 6,
    name: 'Qatar',
    capital: 'Doha',
    population: 812842,
    continent: 'Asia',
    currency: 'Qatari riyal' },
    { id: 7,
    name: 'Mali',
    capital: 'Bamako',
    population: 13518420,
    continent: 'Africa',
    currency: 'West African CFA franc' },
    { id: 8,
    name: 'Bahamas',
    capital: 'Nassau',
    population: 323063,
    continent: 'America',
    currency: 'Bahamian dollar' },
    { id: 9,
    name: 'Australia',
    capital: 'Canberra',
    population: 20155130,
    continent: 'Oceanía',
    currency: 'Australian dollar' },
    { id: 10,
    name: 'Burkina Faso',
    capital: 'Ouagadougou',
    population: 13227840,
    continent: 'Africa',
    currency: 'West African CFA franc' },
];